# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Configs
locale: "zh-CN"
title: 薯条与123
title_separator: "-"
subtitle: 温暖的小窝
name: Fries_I23
email: FriesI23@outlook.com
description: |
  随便写写, 随便玩玩, 随便搞搞

# Structures
# Archives: https://github.com/jekyll/jekyll-archives
# url: https://friesi23.github.io
url: https://play4fun.friesi23.cn
collections:
  posts:
    permalink: /post/:year:month/:slug

# Plugin: Archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - month
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
    month: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
    month: /post/:year:month/

# Theme: minima
# theme: minima
# github_username: FriesI23

# Theme: minimal-mistakes:4.25.0
# Layout: https://mmistakes.github.io/minimal-mistakes/docs/layouts/
# Config: https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# Exmaple: https://github.com/mmistakes/minimal-mistakes/blob/4.25.0/_config.yml
remote_theme: mmistakes/minimal-mistakes@4.25.0
minimal_mistakes_skin: "dirt"
minimal_mistakes_skin_dark: "dark"
repository: FriesI23/friesi23.github.io
copyright: FriesI23
copyright_url: https://creativecommons.org/licenses/by-sa/4.0/
google_site_verifications:
  - RY3mdgt-hVa17vDvoNX0dXcy-V0xpEj8gzRXbtQk7Rw # https://friesi23.github.io
  - uHjDL019v87su5npUUQg7tswRAFU_YVumsmvmwkOl6A # https://play4fun.friesi23.cn
bing_site_verification: 0DF1AC6A81C62171FD53F59652680877
baidu_site_verification: codeva-aQkrzi95GW
comments:
  provider: custom
analytics:
  provider: google-gtag
  google:
    tracking_id: G-2T0DE4DLFQ
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
paginate: 16
paginate_path: /page:num/
search: true
# Tutorial: https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  # tag & category child pages
  - scope:
      path: ""
      type: tag
    values:
      breadcrumbs: true
      comments: false
  - scope:
      path: ""
      type: category
    values:
      breadcrumbs: true
      comments: false
  - scope:
      path: ""
      type: month
    values:
      breadcrumbs: true
      comments: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      show_gh_btn: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      breadcrumbs: true
      show_date: true
      read_time: false
      comments: true
      share: true
      related: false
      toc: true
      toc_sticky: true
      toc_icon: bars
      toc_label: 目录
      show_gh_btn: true
      sidebar:
        nav: projects
      sidebar-op:
        show_categories: true
footer:
  links:
    - label: Github
      icon: fab fa-fw fa-github
      url: https://github.com/FriesI23
  bottom_links:
    - label: 浙ICP备2024100574号
      url: https://beian.miit.gov.cn
      id: sid-cn-record-info
    - label: 网站地图
      path: sitemap.xml
head_scripts:
  - /assets/js/vendor/jquery/jquery-3.6.0.js
  - /assets/js/custom-head.js
after_footer_scripts:
  - https://unpkg.com/vanilla-back-to-top@7.2.1/dist/vanilla-back-to-top.min.js
  - /assets/js/custom-footer.js

# Extra: Id show-only
show_only:
  - id: sid-cn-record-info
    only:
      - friesi23.cn
      - www.friesi23.cn

# Plugin: Gitment
gitment:
  client_id: 6312ebbac9e346953b76
  client_secret: 48e1f1f02f2539efc40ab6e3ec984be42d153202
  owner: FriesI23
  repo: blog-comment
  admin:
    - FriesI23
  distraction_freemode: true
  language: zh-CN

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
whitelist:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - _pages
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - LICENSE
  - README
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ci/
  - templates/
