[tool.poetry]
name = "blog-ci"
version = "0.1.0"
description = "CI scripts for friesi23 blog"
authors = ["FriesI23 <fries22e@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
requests = "^2.32"
lxml = "^5.3"
google-auth = "^2.55.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
